# Generated by Django 2.0 on 2018-03-15 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lyrics', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('year', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SongFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acousticness', models.DecimalField(decimal_places=4, max_digits=5)),
                ('danceability', models.DecimalField(decimal_places=4, max_digits=5)),
                ('energy', models.DecimalField(decimal_places=4, max_digits=5)),
                ('instrumentalness', models.DecimalField(decimal_places=4, max_digits=5)),
                ('loudness', models.DecimalField(decimal_places=4, max_digits=6)),
                ('tempo', models.DecimalField(decimal_places=4, max_digits=8)),
                ('valence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.Song')),
            ],
        ),
        migrations.AddField(
            model_name='lyric',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.Song'),
        ),
    ]
