# Generated by Django 2.0 on 2018-03-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyric',
            name='lyrics',
            field=models.CharField(max_length=10000),
        ),
    ]
