# Generated by Django 2.0 on 2018-03-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_auto_20180316_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyric',
            name='lyrics',
            field=models.CharField(max_length=5000),
        ),
    ]
