# Generated by Django 2.0 on 2018-03-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_auto_20180316_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyric',
            name='lyrics',
            field=models.TextField(verbose_name='Lyrics Field'),
        ),
    ]
